/**
 * Generate authoritative Classic seat values for leaderboard verification.
 * Run: npm run generate:leaderboard-values
 */
import { createRequire } from 'node:module';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getDollarValueForSlot } from '../lib/tradeup/billionDollar';
import {
  DECADE_ERAS,
  decadePlayerToTradePlayer,
  type DecadeEra,
  type DecadeRosterPlayer,
} from '../lib/tradeup/decadeRosters';
import { LINEUP_POSITIONS } from '../lib/tradeup/startingLineup';
import type { Position } from '../lib/tradeup/types';

const require = createRequire(import.meta.url);
const decadeData = require('../lib/tradeup/data/decadeRosters.json') as Record<
  string,
  Record<string, DecadeRosterPlayer[]>
>;

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

type Row = {
  player_id: string;
  primary_position: Position;
  value_pg: number;
  value_sg: number;
  value_sf: number;
  value_pf: number;
  value_c: number;
};

const byId = new Map<string, Row>();

for (const era of DECADE_ERAS) {
  const teams = decadeData[era];
  if (!teams) continue;
  for (const [teamId, players] of Object.entries(teams)) {
    for (const row of players) {
      const player = decadePlayerToTradePlayer(row, teamId, era as DecadeEra);
      if (byId.has(player.id)) continue;
      const values = Object.fromEntries(
        LINEUP_POSITIONS.map((slot) => [slot, getDollarValueForSlot(player, slot)]),
      ) as Record<Position, number>;
      byId.set(player.id, {
        player_id: player.id,
        primary_position: player.primaryPosition,
        value_pg: values.PG,
        value_sg: values.SG,
        value_sf: values.SF,
        value_pf: values.PF,
        value_c: values.C,
      });
    }
  }
}

const rows = [...byId.values()].sort((a, b) => a.player_id.localeCompare(b.player_id));

const jsonPath = join(root, 'data', 'classic-player-seat-values.json');
mkdirSync(dirname(jsonPath), { recursive: true });
writeFileSync(jsonPath, `${JSON.stringify(rows)}\n`, 'utf8');

const esc = (s: string) => s.replace(/'/g, "''");
const lines: string[] = [
  '-- Auto-generated by scripts/generate-classic-seat-values.ts — do not edit by hand.',
  '-- Apply AFTER 20260923_classic_leaderboard.sql',
  '',
  'TRUNCATE public.classic_player_seat_values;',
  '',
];

const BATCH = 200;
for (let i = 0; i < rows.length; i += BATCH) {
  const chunk = rows.slice(i, i + BATCH);
  lines.push('INSERT INTO public.classic_player_seat_values (');
  lines.push('  player_id, primary_position, value_pg, value_sg, value_sf, value_pf, value_c');
  lines.push(') VALUES');
  lines.push(
    chunk
      .map(
        (r, idx) =>
          `  ('${esc(r.player_id)}', '${r.primary_position}', ${r.value_pg}, ${r.value_sg}, ${r.value_sf}, ${r.value_pf}, ${r.value_c})${
            idx === chunk.length - 1 ? ';' : ','
          }`,
      )
      .join('\n'),
  );
  lines.push('');
}

const sqlPath = join(
  root,
  'supabase',
  'migrations',
  '20260924_classic_player_seat_values_seed.sql',
);
writeFileSync(sqlPath, `${lines.join('\n')}\n`, 'utf8');

console.log(`Wrote ${rows.length} players →`);
console.log(`  ${jsonPath}`);
console.log(`  ${sqlPath}`);
